module.exports = {
    REPLACE_ALL: 'REPLACE_ALL',
    ENQUEUE: 'ENQUEUE',
    REPLACE_ENQUEUED: 'REPLACE_ENQUEUED',
    CLEAR_ENQUEUED: 'CLEAR_ENQUEUED',
    CLEAR_ALL: 'CLEAR_ALL',
    AUDIOPLAYER: {
        PLAY: 'AudioPlayer.Play',
        STOP: 'AudioPlayer.Stop',
        CLEAR_QUEUE: 'AudioPlayer.ClearQueue'
    },
    PLAYER_ACTIVITY: {
        IDLE: 'IDLE',
        PAUSED: 'PAUSED',
        PLAYING: 'PLAYING',
        BUFFER_UNDERRUN: 'BUFFER_UNDERRUN',
        FINISHED: 'FINISHED',
        STOPPED: 'STOPPED'
    },
    INTENT_REQUEST: 'INTENT_REQUEST',
    LAUNCH_REQUEST: 'LAUNCH_REQUEST',
    SESSION_ENDED_REQUEST: 'SESSION_ENDED_REQUEST'
};
